name=NeuEEPROM
version=2.0.2
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=Lightweight and safe EEPROM system for ESP32/ESP8266
paragraph=Slot-based EEPROM with alignment, CRC, and safe commit system
category=Data Storage
url=https://github.com/ulywae/NeuEEPROM
architectures=esp32,esp8266
